# Dev tools
brew 'asdf'
brew 'curl'
brew 'fzf'
brew 'git'
brew 'jq'
brew 'neovim'
brew 'tmux'
brew 'watch'
cask 'wezterm'

# Better terminal tools
brew 'bat'
brew 'btop'
brew 'dust'
brew 'diff-so-fancy'
brew 'difftastic'
brew 'dog'
brew 'eza'
brew 'fd'
brew 'git-delta'
brew 'gum'
brew 'ncdu'
brew 'prettyping'
brew 'ripgrep'
brew 'rpl'
brew 'tig'
brew 'tldr'
brew 'tree'
brew 'vale'
brew 'watch'

# Essentials
cask '1password'
cask 'alfred'
cask 'flameshot'
cask 'keybase'
cask 'librewolf', args: {"--no-quarantine" => true }
cask 'obsidian'
cask 'rectangle'
cask 'secretive'
cask 'spotify'

# Better fonts for dev
cask 'font-hasklig'
cask 'font-symbols-only-nerd-font'
