#!/bin/sh

append_to_file() {
  local text="$1"
  local file="$2"

  if ! grep -Fsq "$text" "$file"; then
    printf "\n%s\n" "$text" >> "$file"
  fi
}

install_dependencies() {
  if ! which brew >/dev/null; then
    echo "Brew not found- please install dependencies manually. See the README.md"
    exit 1
  fi

  brew bundle --no-lock -v
  echo
  echo 'Common dependencies installed'
  echo
  echo 'What other apps templates would you like to install?'
  ADDS=$(gum choose --cursor-prefix "[ ] " --selected-prefix "[✓] " --no-limit "personal" "work" )
  for add in $ADDS; do
    echo "Installing $add dependencies"
    brew bundle --no-lock --file=Brewfile.${add}
  done
}

append_git_config(){
  git_config="[include]
  path = ~/.adshell/gitconfig"
  append_to_file "$git_config" $HOME/.gitconfig
}

source_custom(){
  source_cmd="source $HOME/.adshell/custom"

  append_to_file "$source_cmd" $HOME/.bashrc
  append_to_file "$source_cmd" $HOME/.zshrc
}

symlink_gitignore(){
  ln -s ~/.adshell/gitignore_global ~/.gitignore_global
}

symlink_asdf_configs(){
  ln -s ~/.adshell/asdf/asdfrc ~/.asdfrc
  ln -s ~/.adshell/asdf/default-gems ~/.default-gems
  ln -s ~/.adshell/asdf/default-npm-packages ~/.default-npm-packages
}

symlink_configs(){
  ln -s ~/.adshell/config/kitty ~/.config/
  ln -s ~/.adshell/config/wezterm ~/.config/
  ln -s ~/.adshell/config/vale.ini ~/.vale.ini
}

update_terminfo(){
  if type wezterm >/dev/null; then
    ~/.adshell/config/wezterm/install
  fi
}

main(){
  pushd $(dirname $0) > /dev/null
  install_dependencies
  append_git_config
  symlink_gitignore
  symlink_asdf_configs
  source_custom
  symlink_configs
  update_terminfo
  popd > /dev/null
}

main
