#!/bin/sh

append_to_file() {
  local text="$1"
  local file="$2"

  if ! grep -Fsq "$text" "$file"; then
    printf "\n%s\n" "$text" >> "$file"
  fi
}

append_git_config(){
  git_config="[include]
  path = ~/.adshell/gitconfig"
  append_to_file "$git_config" $HOME/.gitconfig
}

source_custom(){
  source_cmd="source $HOME/.adshell/custom"

  append_to_file "$source_cmd" $HOME/.bashrc
  append_to_file "$source_cmd" $HOME/.zshrc
}

symlink_ctags_config(){
  ln -s ~/.adshell/ctags ~/.ctags
}

main(){
  symlink_ctags_config
  append_git_config
  source_custom
}

main
