#!/bin/sh

append_to_file() {
  local text="$1"
  local file="$2"

  if ! grep -Fsq "$text" "$file"; then
    printf "\n%s\n" "$text" >> "$file"
  fi
}

i_use_arch_btw() {
  uname -a | grep -q archlinux
}

install_dependencies() {
  if i_use_arch_btw; then
    sudo pacman -Sy neovim ghostty tmux gum rofi
  else
    install_dependencies_via_brew
  fi
}

install_dependencies_via_brew() {
  if ! which brew >/dev/null; then
    echo "Brew not found- please install dependencies manually. See the README.md"
    exit 1
  fi


  if ! which gum >/dev/null; then
    echo "Gum not found, installing"
    brew install gum &>/dev/null
  fi

  gum spin --title "Installing favourite apps" -- brew bundle --no-lock -v

  echo 'What other apps templates would you like to install?'
  echo '(Use space to select, press return when done)'
  ADDS=$(gum choose --no-limit "personal" "work" )
  for add in $ADDS; do
    gum spin --title "Installing $add apps" -- brew bundle --no-lock --file=Brewfile.${add}
  done
}

setup_git(){
  echo "Setting up git"
  git_config="[include]
  path = ~/.adshell/gitconfig"
  append_to_file "$git_config" $HOME/.gitconfig

  ln -s ~/.adshell/gitignore_global ~/.gitignore_global &>/dev/null
}

source_custom(){
  echo "Setting up custom shell"
  source_cmd="source $HOME/.adshell/custom"

  append_to_file "$source_cmd" $HOME/.bashrc
  append_to_file "$source_cmd" $HOME/.zshrc
}

setup_asdf(){
  echo "Installing ASDF"
  ln -s ~/.adshell/asdf/asdfrc ~/.asdfrc &>/dev/null
  ln -s ~/.adshell/asdf/default-gems ~/.default-gems &>/dev/null
  ln -s ~/.adshell/asdf/default-npm-packages ~/.default-npm-packages &>/dev/null

  asdf plugin add golang &> /dev/null
  asdf plugin add nodejs &> /dev/null
  asdf plugin add ruby &> /dev/null

  asdf plugin update --all &> /dev/null

  echo "Installing Languages"

  V_RUBY="3.4.10"
  V_GOLANG="1.26.5"
  V_NODEJS="26.5.1"
  
  gum spin --title "Installing golang" -- asdf install golang "$V_GOLANG"
  asdf set -u golang "$V_GOLANG"
  asdf set golang "$V_GOLANG"

  gum spin --title "Installing nodejs" -- asdf install nodejs "$V_NODEJS"
  asdf set -u nodejs "$V_NODEJS"
  asdf set nodejs "$V_NODEJS"
  gum spin --title "Installing nodejs packages" -- npm install -g $(cat ~/.default-npm-packages)

  gum spin --title "Installing ruby" -- asdf install ruby "$V_RUBY"
  asdf set -u ruby "$V_RUBY"
  asdf set ruby "$V_RUBY"
  gum spin --title "Installing gems" -- gem install $(cat ~/.default-gems)

  asdf reshim &> /dev/null
}

symlink_configs(){
  echo "Symlinking configs"
  for config in $(ls -1 ~/.adshell/config/) ; do 
    echo "  - $config"
    ln -sf ~/.adshell/config/$config ~/.config/ &>/dev/null
  done

  ln -sTf ~/.adshell/config/claude ~/.claude &>/dev/null
}

update_terminfo(){
  if type wezterm >/dev/null; then
    gum spin --title "Setting up terminfo" -- ~/.adshell/config/wezterm/install
  fi
}

setup_tmux(){
  if [[ -d ~/.tmux-config ]] ; then
    echo "Updating tmux config"
    git clone https://github.com/AdamWhittingham/tmux-config.git ~/.tmux-config &>/dev/null
    ln -sf ~/.tmux-config/tmux.conf ~/.tmux.conf &>/dev/null
  else
    echo "Installing tmux config"
    pushd ~/.tmux-config >/dev/null
    git pull &>/dev/null
    popd >/dev/null
  fi
}

setup_vim(){
  if [[ -d ~/.config/nvim ]] ; then
    echo "Installing vim config"
    pushd ~/.config/nvim >/dev/null
    git pull &>/dev/null
    popd >/dev/null
  else
    echo "Updating vim config"
    git clone -b nvim https://github.com/AdamWhittingham/vim-config.git ~/.config/nvim &>/dev/null
    cd ~/.config/nvim; ./install
  fi
}

pushd $(dirname $0) > /dev/null
cleanup() {
  popd > /dev/null
}
trap cleanup EXIT

install_dependencies
setup_git
symlink_configs
source_custom
setup_asdf
update_terminfo
setup_tmux
setup_vim
