#!/usr/bin/env ruby

require_relative 'lib/deep_merge'
require_relative 'lib/theme'
require_relative 'lib/prompt_modules'

theme = Theme.new
PromptModules.init(theme)
c = theme.to_24bit

lines = []
lines << [
  c.light_blue,
  Path.new(:from_home),
  c.grey,
  Git.new,
  Asdf.new(mode: :only_set),
]
lines << [Cursor.new]


lines.each do |line|
  puts line.join(' ')
end
